---
title: "preliminary results"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,
                      collapse = TRUE,
                      comment = "#>", 
                      fig.path = "markdown/prelim/"
                      )
```

```{r script setup}
library(here)
source(here("code/0-packages.R"))
theme_set(theme_bw())
```

final cores F31, F32 removed

----

# RESPIRATION

```{r flux_files}
flux = read.csv(here("data/processed/flux.csv")) %>% 
  mutate(datetime = ymd_hms(datetime),
         Moisture = factor(Moisture, levels = c("50% WFPS", "100% WFPS")))
```

## CO2 concentrations

**by core**

```{r resp_conc_graph, fig.width=10}
flux %>% 
  ggplot(aes(x = datetime, y = CO2_1_ppm, color = as.character(core)))+
  geom_point()+ geom_path()+
  #geom_point(data = flux, aes(y = CO2_2_ppm), color = "black")+
  facet_grid(Moisture ~ Clay+Temperature)+
  theme_kp()+
  theme(legend.position = "none",
        axis.text.x = element_text(size=10))+
  NULL
```

## CO2 fluxes

**by core**

```{r flux_cores}
flux %>% 
  ggplot(aes(x = incub_days, y = CO2C_ug_g_hr, color = as.character(core)))+
  geom_point()+geom_path()+
  facet_grid(Moisture ~ Clay+Temperature)+
  theme(legend.position = "none")+
  NULL
```

**means**

```{r flux_means, fig.width=6, fig.height=6}

labels = tribble(
  ~Temperature, ~Moisture, ~Clay,
  4, "50% WFPS", "non-amended"
)

flux %>% 
  group_by(Temperature, Clay, Moisture, time, incub_days) %>% 
  summarize(CO2C_ug_g_hr = mean(CO2C_ug_g_hr)) %>% 
  arrange(incub_days) %>% 
  ggplot(aes(x = incub_days, y = CO2C_ug_g_hr, color = Clay))+
  geom_path()+
#  geom_smooth()+
  geom_point(data = flux, size=1.5, alpha = 0.3)+
  scale_color_manual(values = soilpalettes::soil_palette("eutrostox",2))+
  geom_text(data = labels, aes(x = 3, y = 0.12), label = "time zero\n (initial)", color = "black", size=3)+
  geom_curve(data = labels, aes(x = 0.3, xend = 1.8, y = 0.11, yend = 0.12), curvature = -0.3, color = "black")+
  labs(y = "CO2-C, ug/g/hr",
       x = "days of incubation")+
  facet_grid(Moisture ~ Temperature)+
  theme_kp()+
  NULL
```







---

# DOC

```{r doc_files}
doc = read.csv(here("data/processed/doc.csv"))
```


```{r doc_scatter, fig.width=10, fig.height=4}
doc %>%
  mutate(Temp_C = factor(Temp_C, levels = c(4, 20))) %>% 
  mutate(Time = factor(Time, levels = c("Initial", "Final"))) %>% 
  ggplot(aes(x = Temp_C, y = doc_ppm, shape = interaction(Clay, Moisture), color = Moisture))+
  geom_point(size=3, stroke=1, position = position_dodge(width = 0.6))+
  scale_shape_manual(values = c(1,16,0,15))+
  scale_color_manual(values = rev(soilpalettes::soil_palette("redox2",2)))+
  
  labs(x = "Temperature, C",
       y = "WEOC, ppm",
       shape = "",
       color = "")+
  facet_grid(.~Time)+
  theme_kp()+
  theme(legend.position = "right")+
  NULL
```

## summary table

```{r doc_table}
doc %>% 
  mutate(Time = factor(Time, levels = c("Initial", "Final"))) %>% 
  select(doc_ppm, Time, Temp_C, Clay, Moisture) %>% 
  group_by(Time, Temp_C, Clay, Moisture) %>% 
  summarise(doc = mean(doc_ppm),
            se_doc = sd(doc_ppm)/sqrt(n()),
            mean = paste(round(doc,2), "\u00b1", round(se_doc,2))) %>% 
  select(-doc, -se_doc) %>% 
  spread(Clay, mean) %>% 
  knitr::kable()
```

<details>
  <summary>stats</summary>

```{r doc_stats, echo=TRUE}
aov_doc_initial = aov(doc_ppm ~ Temp_C * Moisture * Clay, 
                      data = doc %>% filter(Time=="Initial"))
summary(aov_doc_initial)

aov_doc_final = aov(doc_ppm ~ Temp_C * Moisture * Clay, 
                    data = doc %>% filter(Time=="Final"))
summary(aov_doc_final)
```

</details>


---

<details>
  <summary>Session Info</summary>

date run: `r Sys.Date()`

```{r}
sessionInfo()
```

</details>
